channels:
- conda-forge
dependencies:
- python==3.12
- aiohttp
- cartopy
- cdsapi
- cfunits
- cmocean
- dask
- dask-jobqueue
- distributed
- easygems
- fastparquet
- flox
- hdf5plugin
- healpix
- hvplot
- intake==0.7.0
- intake-xarray==0.7.0
- ipykernel
- iris
- jupyter
- jupyterlab
- jupytext
- libnetcdf>=4.9.2
- matplotlib
- netcdf4
- numba
- numpy
- odc-stac
- opencv
- pandas
- pystac
- pytest
- requests
- rioxarray
- ruff
- s3fs
- scipy
- seaborn
- sh
- spectrum
- tokenizers
- tqdm
- types-pyyaml
- uxarray
- xarray
- xgcm
- zarr
- pip

name: easy