#!/bin/bash

set -vx
prefix=${prefix:-$HOME/python_envs}
name=${name:-easy}
yaml_file=${yaml_file:-environment.yaml}


conda deactivate
mamba deactivate
deactivate

module purge
module load git

set -e

# nvidia-smi || ( >&2 echo  "need a gpu node to get the correct pytorch version" ; exit 1 )

git_version=$(git rev-parse --verify HEAD)
logname="hackathon_env_${git_version}_$(date +%F_%T)_install.log"

if [ ! -d  ${prefix}/miniconda3 ] ; then
mkdir -p ${prefix}/miniconda3
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh -O ${prefix}/miniconda3/miniconda.sh
bash ${prefix}/miniconda3/miniconda.sh -b -u -p ${prefix}/miniconda3
rm -f ${prefix}/miniconda3/miniconda.sh
fi

${prefix}/miniconda3/bin/mamba update -y -n base -c conda-forge conda mamba

command="${prefix}/miniconda3/bin/mamba env create -n easy --file ${yaml_file} -y"
echo $command > ${logname}
echo >> ${logname}

$command >>${logname} 2>&1

# -freeze-installed, --no-update-deps
