channels:
- conda-forge
dependencies:
- python>=3.12
- aiohttp
- cartopy
- cdsapi
- cfgrib
- cfunits
- cf-xarray
- cmocean
- cudatoolkit
- dask
- dask-jobqueue
- distributed
- eccodes>=2.34.0
- ecflow
- ecmwf-api-client
- fastparquet
- gcm_filters
- hdf5plugin
- healpy
- hvplot
- intake==0.7.0
- intake-esm
- intake-xarray
- ipykernel
- iris
- jupyter
- jupyterlab
- jupytext
- libnetcdf>=4.9.2
- matplotlib
- nco
- netcdf4
- numba
- numpy
- ocl-icd-system
- odc-stac
- opencv
- pandas
- pystac
- python-eccodes
- pytorch
- requests
- rioxarray
- ruff
- scikit-learn
- scipy
- seaborn
- sh
- spectrum
- tokenizers
- torchvision
- tqdm
- types-pyyaml
- uxarray
- xarray
- xgcm
- zarr
- pip
- pip:
  - easygems
  - gribscan
name: easy